### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by Ocph23** [octagon-cs/CitraDigitalWebApp#29]
Mohon kiranya design class digram bisa di sertakan dalam issue ini

**Comment by JimLahallo** [comment]
**CLASS DIAGRAM**
![desain sistem_02](https://user-images.githubusercontent.com/39363534/96658605-e80ef200-137f-11eb-96f2-ceb582ec258b.jpg)

**Comment by JimLahallo** [comment]
**Desain Arsitektur**

![ArchitectureDesign](https://user-images.githubusercontent.com/39363534/96658643-0674ed80-1380-11eb-8049-88b234868452.jpg)

**Comment by JimLahallo** [comment]
**Desain Paket**

![desain sistem paket](https://user-images.githubusercontent.com/39363534/96658678-1db3db00-1380-11eb-9788-bf9d47f39834.jpg)

**Comment by Ocph23** [comment]
OK
